name: Frontend Staging CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Frontend to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install pnpm
        run: npm install -g pnpm
        working-directory: frontend

      - name: Install dependencies
        run: pnpm run build
        working-directory: frontend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::381492218855:role/staging-GithubActionsRole"
          aws-region: ap-southeast-1

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://frontend-staging-cdk-workshop --delete
        working-directory: frontend

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id DISTID --paths "/*"
