name: Infrastructure Staging CD Pipeline

on:
  push:
    branches:
      - master
    paths:
      - "infra/**"
      - "lambdas/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Infrastructure to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install
        working-directory: infra

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::381492218855:role/staging-GithubActionsRole"
          aws-region: ap-southeast-1

      - name: Deploy
        run: npm run deploy:staging
        working-directory: infra
