name: Infrastructure Continuous Integration Pipeline

on:
  pull_request:
    branches:
      - master
    paths:
      - "infra/**"
      - "lambdas/**"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Validate Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install dependencies
        run: npm ci
        working-directory: infra

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::381492218855:role/staging-GithubActionsRole"
          aws-region: "ap-southeast-1"

      - name: CDK Synth
        run: |
          npm run synth:staging
        working-directory: infra

      - name: CDK Diff
        run: |
          npm run diff:staging
        working-directory: infra
