name: Infrastructure Production CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Infrastructure to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
